### ISSUE TITLE
CSV File Bug

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#105]
A few weeks ago we introduced we introduced two features in the classificator: 
* to select "not sure"
* variable window length 

As a consequence, there are now : 
* gaps in the labels of files: e.g. we might label 0-2000 ms and 6000-8000ms 
* window lengths could have lengths shorter than 2000ms

Currently, the CSV export in 
https://github.com/rfcx/rfcx-console/blob/master/src/app/components/services/csv.service.js#L34-L39

However has static code that will not handle gaps or variable window lengths.

**Comment by rassokhin-s** [comment]
a note: some of our audio files have `null` site_id in the database, that's why they will be excluded from several results like csv files.

**Comment by rassokhin-s** [comment]
So, I have updated the logic of labels aggregation in API and CSV files generation in front-end.
Now API returns windows duration along with confidences and Console knows the length. Also API fills missing values in gaps with zero.
@daebwae I have deployed the code only to staging, so please check if it works as you expected and I'll push to production. Thanks!

**Comment by rassokhin-s** [comment]
Uploaded to production.
