### ISSUE TITLE
Unfinished Classification "Open-Button"

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#106]
staging-console / Windows Classification:
Unfinished Classification:
If I would like to evaluate a file and cancel without terminating, then appears the button that a file is still open for evaluation. It is working.
I can also press the Cancel button and the message disappears. This also works.
Unfortunately I can not open the file via the green "open" button. Unfortunately, nothing happens.

**Comment by rassokhin-s** [comment]
hey @Starsonic007 could you please describe this situation step-by-step? I just tried it on my local and staging, and it opens back Classificator when I press on `Open` button. Thanks!

**Comment by Starsonic007** [comment]
It just does not work in this particular case.
example
- Open the Windows classifier
- select eg Bus and start the classification
- evaluate a few sequences
- restart the windows classifier
- open the last classification does not work.

**Comment by rassokhin-s** [comment]
@Starsonic007 now it should work fine! :)

**Comment by Starsonic007** [comment]
@rassokhin now it works --> TEST OK
