### ISSUE TITLE
"Complete Button" visible before ending the evaluation 

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#107]
Staging-console: Windows Classification
The "Complete Button" may only be displayed if all sequences have been evaluated in a file.
Currently, the button is immediately visible from the beginning and you can conclude an unrecognized file with it.

**Comment by rassokhin-s** [comment]
hey @Starsonic007, this is a feature that @daebwae added a day ago: https://github.com/rfcx/rfcx-console/commit/fbb46c9c7814f7ece3410322a6cc4dca1d6d8657
I guess it's required.

**Comment by Starsonic007** [comment]
Ok then that fits for me too.
 :-)
