### ISSUE TITLE
Review GuardianAudioEvents 

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#115]
Goal : we need a way to confirm or reject AI generated `GuardianAudioEvents` by a human reviewer. Then we can download only those events that were correctly detected. 

We add a two new columns in the table `GuardianAudioEvents` : 
1. reviewed_by : user_id who reviewed the event
2. reviewer_confirmed: true = it is a correct detection; false=it's a false detection; null=it's not been reviewed

We change the logic of the events endpoint. It has a two new parameters: 

1. omit_false_positives (default=true): true=we return all values where reviewer_confirmed=null or reviewer_confirmed=true; false=no filter
2. omit_unreviewed (default=false): true=we return all values where reviewer_confirmed is not null; false=no filter

As a default we will not return events when a reviewer said it's not a chainsaw etc. . So if we find that a certain chainsaw was not a chainsaw, we can actually omit that from our results. However if a person wants also false detections from our system to gauge the quality of detection, they can do so. 

Now we need a UI Interface to actually set the values for this. Let's first do this in the console and then later also in weirwood. 

In the console, we need a list of all GuardianAudioEvents of a certain `value` like "chainsaw" or "Amazon parrot"; that value can be selected by the user from the possible values saved in `GuardianAudioEventValues`.

After each list item we have two buttons confirm or reject . When one is pressed we submit it to the endpoint and update the event accordingly. We can still change our selection by pressing the other button but we do have a visual indication which button is selected.  

We have a checkbox on top where we can filter out events that were already reviewed so that we only see unreviewed events. 

Bonus Info: at some point in the future, we'll want to add several reviewers for one event. The logic for that would get more difficult pretty quickly. This is why we don't need to add it right now. However, just be aware that this requirement will come some time in the future in case you wonder as it might help you decide on the code complexity.

**Comment by rassokhin-s** [comment]
Just saving info about `omit_false_positives` and `omit_unreviewed` combinations:

omit_false_positives (default: true)
true: null, true
false: null, true, false

omit_unreviewed (default: false)
true: true, false
false: null, true, false

omit_false_positives:true && omit_unreviewed:false => null, true
omit_false_positives:false && omit_unreviewed:false => null, true, false
omit_false_positives:true && omit_unreviewed:true => true
omit_false_positives:false && omit_unreviewed:true => true, false

**Comment by rassokhin-s** [comment]
When user opens the page, he can choose event value from the dropdown and load events. Then he will see a table with results. First column is event guid, second - name of latest reviewer (if it was reviewed) and result of review (true || false || n/a).
![screenshot_stanislav 2017-04-06 15 23 23](https://cloud.githubusercontent.com/assets/2122991/24753928/0174b198-1add-11e7-98b8-fa772ae1271f.png)

Then he can review any event by pressing View button. After pressing it, the audio file and spectrogram starting to load and selected row is being highlighted.
![screenshot_stanislav 2017-04-06 15 22 36](https://cloud.githubusercontent.com/assets/2122991/24754025/752c657c-1add-11e7-803c-576b2fd16117.png)

Spectorgram with audio appear below the table. User can listen to audio file and confirm/reject event existence. Then he can press Close button or choose another event by clicking on View button without clicking on Close.
![screenshot_stanislav 2017-04-06 15 22 42](https://cloud.githubusercontent.com/assets/2122991/24754082/af7f6738-1add-11e7-8ba5-c4e01260d26c.png)
