### ISSUE TITLE
Guardian Overview

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#118]
Currently: we have an overview of guardians by site. 
Goal: we'd like to have also a general overview of all guardians anywhere. 

Details: 
Now that we have a new way to select global categories rather than just by sites, we add a new item there that's an overview of all guardians. The new tab is called "Statistics" . 

We'll have a button array on the left as we have now for the sites. The first button is the new "Guardian Overview". 

When a user clicks that button, they'll get an overview of all guardians with three columns: 
* Guardian name 
* Last Uploaded Audio (Time Since)
* Last Uploaded audio (Date / time)
* Last Checkin (Time Since)
* Last Checkin (Date / Time)

We can order by "Last Uploaded Audio" or "Last Checkin". 

The (Time Since) has the following formats: 
* < 1 minute 
* 2 hours, 30 minutes (for anything less than a day)
* 5 days (for anything of at least one day)

**Comment by daebwae** [comment]
The distinction of a a few seconds ago and a minute ago; I'd drop it and say to both "a minute ago"

**Comment by rassokhin-s** [comment]
@daebwae this is a build-in moment.js method http://momentjs.com/docs/#/displaying/from/
if you really want to use `a minute ago` for both, I'll need to write our custom method. It's not a problem, just wanted to check again before doing that.

**Comment by daebwae** [comment]
@rassokhin-s  If it's not a custom function yet and we are using a standard package. Let's define the custom properly first and create a new task for that. I'll close this task and put it on my todo. Thanks for the feedback!
