### ISSUE TITLE
Changes to guardian listing

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx-console#12]
In the list of guardians on the main page (with the map) let's change the way things are written:

Currently it looks like this:
`guardian_name ( xx seconds ago )`

1. Please add the first four letters of the guardian_guid in parenthesis after the name
2. Instead of using the long word "minutes" please use "mins"
3. Instead of using "seconds" say "< 1 min"

So it would look like this:
`jacob (d2f4) — < 1 min ago`
`jacob (d2f4) — 18 mins ago`
`jacob (d2f4) — 3 hours ago`
`jacob (d2f4) — 2 days ago`

**Comment by topherwhite** [comment]
Looking good! We may make subsequent changes, but everything requested was built. Thanks

**Comment by topherwhite** [comment]
There seems to be a discrepancy when the non-plural "minute" is used (for "1 minute ago") 
See screenshot:
![image](https://cloud.githubusercontent.com/assets/1895255/10420471/a64cdf78-7049-11e5-8b90-bc333903f22c.png)

**Comment by sweety-wo** [comment]
that was silly mistake..it is resolved now..

**Comment by topherwhite** [comment]
Looks good. More changes later, but you got all of these for now.
