### ISSUE TITLE
Guardian Overview & Table Component

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#121]
The data table component (also used in the Guardian Overview) is expanded by a new feature. The feature allows us to select which columns are being displayed. The selection of the user is stored in localStorage. This way users can focus on the information that matters to them on any given page.

**Comment by rassokhin-s** [comment]
For the current moment we save user selection in localStorage only for time when he is on the page - in other words, page saves states after new data is loaded.
