### ISSUE TITLE
Queue Up Files For the model 

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#126]
Currently we need to queue up model files by hand via: 

/v1/guardians/8e3df75a9e16/audio/analysis?ending_before=2016-11-19T00:00:00.000Z&starting_after=2016-11-18T00:00:00.000Z&model_id=47673e78-5b55-4c0f-a486-43afecaefb74

We need a simple UI in the AI section of the Console. There we add a new left-icon. 

Within it we allow to select: 

* a model
* a guardian
* a start time 
* and end time 

And then we use the above like route to queue up those files for processing.

**Comment by rassokhin-s** [comment]
@daebwae @topherwhite just info: we have `POST` endpoint, but use query attributes. It works, but it's not good :) I was stuck with: "Omg, why my request has error response?" until I found that I need to send query instead of body attributes. :)

**Comment by rassokhin-s** [comment]
@daebwae yeah, but we don't have exact CRUD scheme of API. We have many different endpoints. That's why I thought that in `POST` we often use `body` to send data, but not query. But your idea of using query for data which not meant to be saved, but only used, looks very interesting to me. Thanks.
