### ISSUE TITLE
Guardian Geo-Data

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx-console#13]
To build and test this function, please use the "cerroblanco" site. The two guardians within Cerro Blanco have accurate geo-coordinates, returned by the API endpoint.

`GET /v1/sites/cerroblanco/guardians` returns an array of guardians, which now include a `location` parameter with `latitude` and `longitude` (as part of the guardian object).

Please add markers on the map for each guardian. When a guardian is clicked/selected from the list, the map should "zoom and pan" toward the marker.

Let's try some options with customizing the CartoDB marker icons, including adding labels that show the guardian name.

Thanks!

**Comment by rassokhin-s** [comment]
@topherwhite please re-open if smth need to be updated here.
