### ISSUE TITLE
Labels on Guardian Map

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx-console#17]
Currently, it appears that the guardian map labels (the labels that show which pin/icon corresponds to which guardian) only show for one of the items (the last one rendered). This is presumably because you are using "popups" to show the labels (hence the little x button the label box). This is not best practice, and it also imposes the limitation of only being able to show one label.

It seems extremely likely that the CartoDB JS API allows for labeling of icons (without doing it as a popup hack) please make use of this instead of the current hack, and also make sure that labels are compactly shown for all pins.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/167270113296771/167312670106718)

**Comment by topherwhite** [comment]
This is looking good. One thing though... the labels often overlap for guardians that are close to each other. This might not be something that Leaflet can detect, in which case don't worry about it. But if there's a simple way to make the labels move around the pins without overlapping, let's try that (I notice that somewhat randomly the labels seem to change sides)

**Comment by rassokhin-s** [comment]
@topherwhite still an issue?

**Comment by rassokhin-s** [comment]
@daebwae actually there is no option for labels to move around other pins. Since we have a separate map for each guardian and often see one pin at each map, I guess this issue is not so important.
If it's still requires to be updated that I can work on modifying lib's code.
