### ISSUE TITLE
"Fit Bounds" of Guardian Map to the markers that are displayed

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx-console#21]
When rendering the map for the first time, the zoom/bounds of the map should be determined by the markers (guardians) that are shown.

This should be do-able using something similar to (if not identical to) `fitBounds()` in Leaflet.js, as demonstrated in this MapBox example:
https://www.mapbox.com/mapbox.js/example/v1.0.0/fit-map-to-markers/

This should only happen when the map is first loaded—it should not happen when the guardian list refreshes in the background.

NOTE: Still do to: when a Guardian is selected from the list, zoom the map to the guardian marker. It would also be cool if the marker label changed color somehow to indicate that it's been selected.

Thanks!

**Comment by topherwhite** [comment]
Confirmed this is working.

I'm hoping you can put in some margins (programmatically) so that the guardians are not right up against the edges of the map. There needs to be a little bit of space.

I like that the maps pans to the guardian when it selected. It would also be good for it to zoom in a bit at the same time.

Finally (although this might be because it's a work-in-progress) I noticed that that maps resets to fitBounds whenever it updates the guardian list from the API. This should be changed to only occur when the map is initially loaded.

Thanks!

**Comment by rassokhin-s** [comment]
@topherwhite please re-open if smth need to be updated here.
