### ISSUE TITLE
Add a few more controls to the map interface

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx-console#22]
It would be cool to start using the map a little bit more.

One of the first features to add would be a toggle between various background tiling.

As a first step, let's try one for the satellite. This may need to be explicitly referenced to a MapBox tile definition... so after you've looked into this a little, let's discuss.

Thanks!

**Comment by rassokhin-s** [comment]
@topherwhite please re-open if smth need to be updated here.
