### ISSUE TITLE
WebAudio Visualization: For live Equalizer/Spectrum, add an axis (coordinates)

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx-console#23]
The live spectrum analyzer is looking great.

Do you think we could add some axis to the visualization? It should be very subtle.

The horizontal axis is "Frequency" and ranges from 0 -> half of the sample rate. So, with the current audio, that's ~4000. I think with the Fast-Fourier-Transform algorithm you're using, it's probably more like 0 -> 4096... but basically, this is something that I'm hoping the WebAudio code will actually tell you, and you can put it onto the canvas.

Here's a quick mockup of what I'm imagining:
![file_000](https://cloud.githubusercontent.com/assets/1895255/10961915/9e370b12-837a-11e5-824b-6964ea2c1432.jpeg)

**Comment by rassokhin-s** [comment]
@topherwhite please re-open if smth need to be updated here.
