### ISSUE TITLE
DateTime Slider Changes

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx-console#24]
We are soon going to be able to start using the datetime slider... :-)

However, as I've come to better understand how it will be used, I've realized that it will *never* need two draggable elements. At the moment it has one for the beginning and one for the end.

Please remove one of the two slidable elements.

Also, as a default (until the API provides you with a valid data), please set the "beginning date/time" of the slider to 24 hours prior to the current time (that's the point way over on the left). The right-most point on the slider should be the current time.

For now, the default location of the draggable element on the line should be over on the right, near the current time.

Eventually, the default position will be determined by the latest data, but let's get to that after you've implemented the above changes. Thanks!

**Comment by topherwhite** [comment]
Also, as the draggable element is moved back and forth on the line, some client side variable should be updated to indicate what date/time it now represents. This date/time should be displayed above the draggable element, and should move with it (if possible).

Let me know if you require some clarification on this...

Thanks!

**Comment by rassokhin-s** [comment]
@topherwhite please re-open if smth need to be updated here.
