### ISSUE TITLE
Diagnostic Charts: "Network Strength" 

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx-console#26]
At the moment, the Network Strength chart looks like this:

![image](https://cloud.githubusercontent.com/assets/1895255/10965278/0192e5ce-8393-11e5-925b-2cefbb9aeaea.png)

To make this chart more readable and usable, we will need to change a few things about how it is displayed:

The raw data values provided by the API are integers from -50 to -130. 0 is also a possible value. These are "dBm" values for the strength of the cell network (decibel-milliwatts). It's a useful metric, but it cannot be charted explicitly without being modified.

1. Convert the raw values into chartable values. We'll call the "raw values" `x` in the equation below.
  - Calculate a power value like this `10^(x / 10)` 
  - The result should be a really tiny double floating point, like 5.011 x 10^-12. Regardless, put these values into the chart and graph them in relation to each other.
  - If the raw value is zero, then don't calculate anything—just use zero.

2. Chart those new values!
  - Although the position of the points will determined by the calculations above, please don't display those numbers on the chart.
  - If possible, please display the raw value (-50 to -130) in association with the points on the chart.

3. Label the points, if reasonable
  - Each JSON data point (`signal_strength`) should come with some extra meta data, namely `carrier_name` and `network_type`
  - For now, let's just use `network_type`. How can we associate these attributes with each individual data point? Can it be visible on hover (similar to the way show the value right now)?

**Comment by rassokhin-s** [comment]
@topherwhite still an issue?

**Comment by daebwae** [comment]
Could we investigate if this is still an issue? If it's not we could close the task?

**Comment by rassokhin-s** [comment]
@daebwae Actually moving to `10^(x / 10)` does not give us any effect. On the contrary - some values start being missing. Here are two screenshots for one period of time, but different calculations:
1) as it was (raw values)
<img width="1013" alt="screenshot_stanislav 2016-08-03 10 35 37" src="https://cloud.githubusercontent.com/assets/2122991/17357592/3dc95b0a-5966-11e6-943f-b248ca3280cc.png">
2) Using `10^(x / 10)`:
<img width="1013" alt="screenshot_stanislav 2016-08-03 10 36 23" src="https://cloud.githubusercontent.com/assets/2122991/17357591/3dc95736-5966-11e6-9824-f6b68eebbf96.png">
On the second screenshot labels for `-89` are missing.

My suggestion is stay raw values as it was. What do you think?

**Comment by Starsonic007** [comment]
Hey @daebwae 
Did it work fine ?  Could you please check the Task ?

![image](https://cloud.githubusercontent.com/assets/20114180/18230686/f4d281d6-72a3-11e6-9338-9303c6552836.png)
