### ISSUE TITLE
Toggle button must have neutral color

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#29]
Currently the Toggle button has the same color as the decision of the Gaia Classification.
In order not to affect the user in his decision, the toggle button needs to have a neutral color

Once the user has made a decision, the color as before should be red or green.
Decisions on the toggle button should *not *affect or change the values of Gaia Classification.

**Comment by Starsonic007** [comment]
The toggle button has been removed. The classification will be made on 2 new buttons: "Ambient" and "Engine"
The buttons now have a neutral white color. After pressing the selected button, it will change the button-color from white to gray
If you change your selection, also the color of the button is changed.
