### ISSUE TITLE
Auto-Scroll Windows

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#32]
New Workflow (Changes are bold) 

Sheridan wants to classify all windows for one file in one go. Sheridan likes to use the keyboard. Currently whenever he gets to the center of classification he has to use the touchpad to scroll the windows to the left. As he's got to classify a few hundred files, this is becoming an issue for him.  

Solution: 

Initial Phase = First Window => No scrolling
1. Sheridan presses the Play Button
2. The first window is played 
3. Sheridan classifies the window

Auto-Scrolling Phase 
4. The second window is played 
5. Sheridan classifies the second window
6. The system scrolls the window to the left: The second window is now at the place of the first window...
goto 4 

End Phase => Next to last window => No scrolling

**Comment by Starsonic007** [comment]
[](url) #41

**Comment by Starsonic007** [comment]
Task was reacted as described in Requirement  --> TEST OK
