### ISSUE TITLE
Remove Overlays

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#33]
Frank is a visual person. He has learned to identify trucks, bikes, ... from the spectrogram alone. The better he can see the spectrogram, the easier it is for him to classify it. Frank, however, can't properly identify the colors in the spectogram because wavesurfer's overlay and the background color of the window are obscuring his view. At the same time he needs to know which window he's currently classifying. 

Therefore, we want to remove all overlays and just keep the the frames for the windows to help determine what portion of the file and spectogram he's classifying.

**Comment by Starsonic007** [comment]
UI has been adjusted and currently there are no suggestions for improvement  --> TEST OK
