### ISSUE TITLE
The spectrogram is shifted by 2 sequences too far to the right.

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#34]
The spectrogram is shifted by 2 sequences too far to the right.

<img width="354" alt="spectogram zu weit rechts" src="https://cloud.githubusercontent.com/assets/20114180/16315684/8cc7a7a0-3983-11e6-969a-59c7238ef031.png">

**Comment by rassokhin-s** [comment]
It's normal when audio and spectrogram have a gap at the beginning. It happens because our audio files have a no-sound gap in the start of each file (related to audio encoding on android). If you found this something abnormal, please provide additional details how can I repeat this on my end.

**Comment by Starsonic007** [comment]
The problem was not, that the first two sequences were silent, the Spectogramm was 2 sequences to far to the right

Now fit sequences and spectrogram back together

TEST --> OK
