### ISSUE TITLE
The scrollbar under the sequences is no longer visible.

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#35]
The scrollbar under the sequences is no longer visible.
Already rated sequences can not be heard again because you can not scroll to the first sequence of streams

**Comment by rassokhin-s** [comment]
It is visible for me. If issue still exists please let me know

**Comment by Starsonic007** [comment]
The issue can be closed. I tested it with the touchpad of my Macbook and an external mouse.
The scroll bar is visible only if you have connected an external mouse. That's OK.
 —>  Retest successfully
