### ISSUE TITLE
Hear one sequence before

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#36]
Problem: If you now want to listen the rated sequence again and click the arrow buttons to the left. Currently you don´t hear the same sequence again. You hear one sequence before. That is not correct.

**Comment by rassokhin-s** [comment]
Discussed with Chris in Slack - he didn't found the issue last time. Closing until it happens again (if happens :-))

**Comment by Starsonic007** [comment]
Yes.. :-) 
Error no longer reproducible. Bug closes
