### ISSUE TITLE
Labelling: GUID Selection

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#43]
**Currently**: we select the next audio file to label from the GUID retrieved from `/datafilters/labelling` . 

**The problem**: Sometimes, however, we need to specifically label one audio file because we want to validate the model's classification.

**The solution**: As a annotator, I want to jump directly to an audio file by supplying a GUID in order to validate the model's classification. As a first step, we can supply the GUID via a GET parameter in the URL when we open up the labelling/classification screen.

**Comment by rassokhin-s** [comment]
Now it's possible to open specific audio by typing guid in url params.
Example: http://staging-console.rfcx.org/#/classification/derc?guid=2fb84c4f-b08d-4cf3-ade7-9568370cdcc2

**Comment by Starsonic007** [comment]
It's possible to open specific audio. You can tag a file,  change the URL and it opens the Classificator with the correct file --> TEST OK
