### ISSUE TITLE
Site -> Guardian -> Stream: Label the current audio file

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#45]
*Currently*: In the stream, we can listen to audio files at any point in time. In the labelling application, we can label a specific audio file with the GUID in the GET parameter. However, we cannot seek within a stream an interesting event within the audio stream and then label it. 

**User Story**: As a audio analyst or ranger, I'd like to seek through the audio stream,find interesting events like chainsaws and click a button "label file|" to switch over to the labelling application. The GUID of the audio file we currently playing is used as a GET parameter in the labelling app.

**Comment by Starsonic007** [comment]
Detectons --> Stream --> tag file
if you push the button "tag file" --> the Classificator opens and in the  address line you find the GUID

![image](https://cloud.githubusercontent.com/assets/20114180/17525730/4da1f0c0-5e64-11e6-950d-822e154b804e.png)

**Comment by Starsonic007** [comment]
![image](https://cloud.githubusercontent.com/assets/20114180/17525799/aa9c1a26-5e64-11e6-9e61-36100ccdeae6.png)

**Comment by Starsonic007** [comment]
Test OK
