### ISSUE TITLE
Classification: Add Class Selection

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#46]
**Currently:** we go straight to the classification after clicking the window classification button. 
**Problem** as we want to allow for vehicle, chainsaw and possible other classifications, we want to add another screen before the classification
**Story** as an audio analyst, I want to select either chainsaw or vehicle to classify occurences of these types. Additionally, a biologist may want to be able to simply add a custom label and classify audio files with that to add their special knowledge about a bird species they can recognize but we don't supprot yet.

![image](https://cloud.githubusercontent.com/assets/749854/16673832/029aaa02-44b2-11e6-9a5b-e201a3da5de0.png)

**Comment by daebwae** [comment]
![image](https://cloud.githubusercontent.com/assets/749854/16674063/b969fcea-44b4-11e6-86d3-47a2e95642d9.png)

**Comment by Starsonic007** [comment]
Before starting a classification, opens a window where I can choose between chainsaw, vehicle or something else.
Having made a selection, opens the classifier.
If I want to classify something else then the registered name is entered in the button on the next page.
--> TEST OK
