### ISSUE TITLE
Classification: Tag anything

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#47]
**Currently**: the classification allows to only tag engines. 
**Story**: as a data analyst, I'd like to be able to tag anything really in order for us to train new models  that can recognize any sound around the world. 

To keep things simple, we will: 

It wouldn’t change much, we just need to replace the word ‘Engine’ by ‘vehicle’ or ‘chainsaw’ (depending on our selection) or  a custom tag. Then we save the tag value ‘vehicle’ or ‘chainsaw’ or the custom value. Instead of using the `/datafilter/labelling` endpoint, we will use `/datafilter/labelling/{currentTag}` to select the next guid. Everything else stays the same.

**Comment by Starsonic007** [comment]
Now you can choose between 2 different reviews. Either you rated the sound of a chain saw or the sound of a vehicle

If you click the button for chainsaw, the Classificator and the labeling of the buttons is now open to "Ambient" and "Chainsaw". -> TEST OK

Clicking on the button Vehicle, gets the rating button in Classificator the name "Vehicle" -> Test OK

It has further the possibility to choose the Labeling a button itself. Here you have to enter the name in the free text box, which is then also new to see in Classificator on the button. -> TEST OK
