### ISSUE TITLE
Overhaul UI for Login & Register screens

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx-console#5]
Just looking to move some things around and establish a general style when it comes to text entry fields and forms within the web app. Generally, we'll be looking to simplify the UI wherever possible (fewer icon & buttons) and almost always use oversized text fields and text. I'm going to refer to the Slack login page as an example, but there are many such examples of this out on the web. See screenshots below to get started and speak with @topherwhite for details if necessary.

1. remove background image (it didn't stretch on oversized monitors anyway)
2. Instead of tabs for Login/Register, these should be totally different pages/urls
3. Change the style of the fields (bigger, no icons on the left, more spacing). Use the Slack screenshot as an example

![image](https://cloud.githubusercontent.com/assets/1895255/10261466/c066a2d8-6999-11e5-8947-83d32f33402f.png)

![image](https://cloud.githubusercontent.com/assets/1895255/10261467/ca8361ac-6999-11e5-8c7f-9fd7966de536.png)

**Comment by topherwhite** [comment]
Great changes, thanks!
This is almost exactly as I'd hoped for, but I'm gonna be difficult and request a couple small changes:
1. Please make the text box font size about 25-33% larger
2. On the Register page, let's put a separator line (similar to an `<hr/>` element) in between the Invite code and the other text boxes.
Thanks!

**Comment by sweety-wo** [comment]
Done as per @topherwhite comments..

**Comment by topherwhite** [comment]
Looks good!
