### ISSUE TITLE
wipe on the mouse pad of the Mac

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#53]
Windows Classification
If you can quickly wipe with 2 fingers on the mouse pad of the Mac to the left, then you will be thrown out of the Classificator and all already assessed sequences are away.
![image](https://cloud.githubusercontent.com/assets/20114180/16923814/82eb612a-4d1c-11e6-845f-eccdfcb2eb8d.png)

**Comment by rassokhin-s** [comment]
Hey @Starsonic007. I know about this situation on Macs. But this is default behavior of touchpads:
- fast swipe goes back in browser's history
- slow swipe scrolls horizontally
So this could be repeated on any site in the world :)
I think you just need to be careful when you swipe touchpad.

If you meant something different, please explain. Thanks!

**Comment by rassokhin-s** [comment]
After talking with Stefan we decided to save current data in local/session storage and load it then if classification was interrupted.

**Comment by rassokhin-s** [comment]
Here is the flow:
Now currently opened audio and windows are being saved to localStorage.
If you accidentally or specially change the page "in the middle of the road", then you'll see a bouncing balloon in the bottom right of the window:
<img width="259" alt="screenshot_stanislav 2016-07-21 14 10 44" src="https://cloud.githubusercontent.com/assets/2122991/17020980/5f664e9e-4f4d-11e6-9984-7eb27aac8446.png">
Then you can hover over it and see two buttons: Clear and Open
<img width="217" alt="screenshot_stanislav 2016-07-21 14 10 58" src="https://cloud.githubusercontent.com/assets/2122991/17020990/70999e00-4f4d-11e6-91e6-15e81c2e7069.png">
"Clear" clears your progress in audio classification and "Open" opens a Classifications page with unfinished audio and saved progress of windows classifications.
<img width="1385" alt="screenshot_stanislav 2016-07-21 14 16 02" src="https://cloud.githubusercontent.com/assets/2122991/17021021/baa709ba-4f4d-11e6-9329-32c21f7d253a.png">

**Comment by Starsonic007** [comment]
That is a very good idea.!
Now all previous classified sequences are stored as soon as the Classificator is terminated and you have to evaluate outstanding sequences. -> TEST OK
If the Complete button is pressed and it ends the Classificator - more messages are displayed 
 -> TEST OK
