### ISSUE TITLE
Add a model performance overview 

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#56]
**Background**
We need a way to meassure and display our models (or AIs, more widely used but I find it a bit misleading) performance/accuracy on two metrics: 
1. [Precision](https://en.wikipedia.org/wiki/Precision_and_recall#Precision): the model detects a chainsaw and we measure how often the model is correct. If the model tags 100 windows as chainsaws and our classifiers/annotators tag 95 of those also as chainsaws, the precision is 0.95 .
2. [Recall](https://en.wikipedia.org/wiki/Precision_and_recall#Recall): this measures how many times the model didn’t send an alert but there was actually a chainsaw going off. If our annotators/classifieres tagged 100 instances of chainsaws and the model detected 80, it’s recall is 0.8 

**UI**
We have four controls on the landing page: 
1. A Dropdown Box to select the model (you can find the information to populate the drop down in the AudioAnalysisModels) 
2. A short summary box with the overall precision and recall of the model for all audio files 
3. A table where the rows are one audio file each and the following columns 
   3.1. GUID of the audio file
   3.2. Start Time of the audio file 
   3.3. Duration of the audio file 
   3.4. Precision of the audio file
   3.5. Recall of the audio file 
   3.6. A column for the fourth control 
4. A button to jump to the audio file of the table row (this is 3.6) 

When we click (4) we use the classification UI where we can play the audio. However, beneath the classification windows, we see different rows. One for each model and user who labelled/classified the file. They are red for chainsaws and green for ambient depending on the confidence. 

**SQL** 
For the **Download Tab**, we already have a way to query the tags from all users and files. This can be used to calculate the recall and precision. A similar query can be used for the models. If any help is needed please let me know.

**Comment by daebwae** [comment]
Precision SQL
SELECT m.audio_id, count(*) FROM 

(SELECT audio_id, begins_at_offset, ROUND(AVG(confidence)) as confidence 
FROM GuardianAudioTags 
where type="label" and value="chainsaw" 
group by audio_id, begins_at_offset) u

INNER JOIN 
GuardianAudioTags m 
ON u.audio_id=m.audio_id and u.begins_at_offset=m.begins_at_offset and u.confidence==m.confidence
where m.type="classification" and m.value="chainsaw"  
group by m.audio_id

**Comment by daebwae** [comment]
SQL Recall

SELECT u.audio_id, count(*) FROM 

(SELECT audio_id, begins_at_offset, ROUND(AVG(confidence)) as confidence 
FROM GuardianAudioTags 
where type="label" and value="chainsaw" 
group by audio_id, begins_at_offset) u

LEFT JOIN 
GuardianAudioTags m 
ON u.audio_id=m.audio_id and u.begins_at_offset=m.begins_at_offset and m.type="classification" and m.value="vehicle" 
where m.tagged_by_model is null
group by u.audio_id

**Comment by rassokhin-s** [comment]
Task is done and tested locally. On hold by the moment when we get real data on production server.
![screenshot_stanislav 2016-08-01 22 15 52](https://cloud.githubusercontent.com/assets/2122991/17305895/b0a8c1b0-5835-11e6-844a-9280bc6c81dc.png)

**Comment by Starsonic007** [comment]
Common performance does not appear on every model.
Ex:
![image](https://cloud.githubusercontent.com/assets/20114180/18065542/8ad86a48-6e34-11e6-809f-daa80a0dff0b.png)

[https://github.com/rfcx/rfcx-console/issues/81](url)

**Comment by Starsonic007** [comment]
TestResult in the File Attachment 
@rassokhin-s   must I also test the calculation behind the precisions?
#81 
[~$nsole 56.docx](https://github.com/rfcx/rfcx-console/files/445602/nsole.56.docx)

**Comment by rassokhin-s** [comment]
@Starsonic007 thank you a lot!
Yeah, it would be cool, if you could test calculations for some of files. I've tested it, but double-check would be great :)

**Comment by Starsonic007** [comment]
This task has now been tested several times. I currently have no other errors detected. That's why I close this task.
