### ISSUE TITLE
Classification: Audio Id Information

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#57]
Add guid of the audio file, it's meassurement time and guardian guid to the classification window.

**Comment by Starsonic007** [comment]
![image](https://cloud.githubusercontent.com/assets/20114180/17333378/7402349c-58d2-11e6-8417-ff64ff770df3.png)

now the 
- Audio guid
- Measured at	
- Guardian guid	
 is visible --> TEST OK
