### ISSUE TITLE
Diagnostics: Current Time issue

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#61]
If we visit the page at 4pm, stay on it for an hour (5pm), then we want to check the current time but the rightmost slider position is still 4pm. We could have a update button that would update the slider to include the current time (5pm) or we could auto update the timescale to include the current time.

**Comment by Starsonic007** [comment]
the timeline is refreshing every 5 minutes and the proceeds. the timeline is not standing still --> TEST OK
