### ISSUE TITLE
after classification  a  tag-file

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#63]
Side -> Stream -> tag file

When I press the "tag file" button, a new tab will open. That's OK

But if I have now reviewed the "tag-file", I can then press the "Complete Button". This is also OK. But when I again want to change something afterwards, then I can not press the "complete button" again. He remains grayed out.

[https://github.com/rfcx/rfcx-console/issues/45](url)

**Comment by rassokhin-s** [comment]
We decided with @daebwae that we disable that button for a while. Updating saved tags requires some changes in the API.

**Comment by rassokhin-s** [comment]
Now it's available to save changes.

**Comment by Starsonic007** [comment]
After the evaluation, it is now possible with the "NEXT button" to reach another unvalued file --> TEST OK
