### ISSUE TITLE
Check for client/server time mapping when creating request on Downloads page

### ISSUE THREAD

**Issue by rassokhin-s** [rfcx/rfcx-console#64]

**Comment by Starsonic007** [comment]
I tagged a file, and then download this file on the audio download page. The times are the same extent. 
@rassokhin-s  :  Generally, there is a problem with the time (UTC, LOCAL, Guardian Time) . There are differences in the display. Ex Site -.> Stream to Classificator
If you tag a file, the time is different to Classificator
