### ISSUE TITLE
What happens with the files once they have been evaluated

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#67]
Model performence -> Audio Performance

What happens with the files once they have been evaluated. The list would be used longer and I see currently no priorities of the individual files.

**Comment by rassokhin-s** [comment]
Hey @Starsonic007. Could you please describe your question more deeply? I cannot understand what you mean here :) Thanks!

**Comment by Starsonic007** [comment]
Sorry @rassokhin-s if I have not been described so accurately.
My question at this point is: What is currently happening at this point? I have here an ascending number of audio files. These are also more and more. The files can be neither ranked nor "processed". Are the files sorted by priority? What happens to these files, when I got my information?
Perhaps I can explain it at another example.

Under the field "Performance by Audio" there was the field
"Audio Classified by model not by User" or so. 

Here it was: if the file was evaluated, it goes up to the "Performance by Audio". The file has been postponed and  was "finished"

Sorry for my bad english :-/

**Comment by rassokhin-s** [comment]
Currently we have three tables on this page which represent some model performance:
I'll start from the second table.
2 table is "Performance by Audio" - shows precision and recall for each audio file classified by model
`precision = events correctly detected by the model / events detected by the model`
`recall = events correctly detected by the model / events detected by the user`
1 table is "Common performance" - it shows average values for performance and recall for the model. but it's calculated not by sum of all precisions and dividing by their count. It's calculated by sum of all `events correctly detected by the model` dividing by `events detected by the model`. The same for recall
3 table is "Audios classified by model, but not classified by users" which helps us to see what audio files we need to classify by ourselves to get 2nd and 1st tables refreshed with new values. So when we press an Open button, classify this audio file and refresh performance data, we see that this file is gone from 3rd table and appended to 2nd table.
There is no priority in these tables - all values are sorted by audio id.

Sorry @Starsonic007  if I didn't understand your question again :) But I tried to understand what you meant :)

**Comment by Starsonic007** [comment]
Hy @rassokhin-s .
This morning I had a call with @daebwae , and he explained to me how the site is to use.
I thought the rated files still need to be further processed. But the files are indeed collected training data for the model. Sorry for the misunderstanding .. You can close the question ..

**Comment by rassokhin-s** [comment]
Thanks Chris!
