### ISSUE TITLE
Model Performence Page "LOAD" Button 

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#69]
performance
Model Performence Page

When selecting a new model from the drop-down, the "Load" button appears. Once the model has been loaded, the "Load " button should disappear. Now if you want to select a new model, the model should be charged directly to the dropdown selection.

**Comment by rassokhin-s** [comment]
Hey @Starsonic007 I'm not sure if we need to hide Load button after the data is loaded - I'm speaking about case when we want to load fresh data for the current model (for example after 10 minutes). If we hide this button, then we need to select another model, select current model again to make Load button visible.

**Comment by Starsonic007** [comment]
Hey @rassokhin-s 
You have the better arguments :-) Your right. When I like to update the model, my imaginary approach is not practical.

**Comment by rassokhin-s** [comment]
Then I guess we can close this issue. Thanks!
