### ISSUE TITLE
Search Function in Windows Classification

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#70]
Would it be possible to incorporate a search function?
I think it might be helpful if you can also search for a specific GUID. I thought of something like this.

![image](https://cloud.githubusercontent.com/assets/20114180/17643575/a08c68bc-616e-11e6-9bcd-2134ce390595.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/167270113296771/167541106046891)

**Comment by rassokhin-s** [comment]
Hey @Starsonic007 It's possible. But... do we really need this? I cannot imagine cases when I need to search audio file by GUID - they are so randomized! Generally if I want a specific file, I already have a GUID number, then I put it in url params. What I can do in this case - add an input where user can paste his GUID number and it will be used. 
What do you think of that?

**Comment by Starsonic007** [comment]
Hello @rassokhin-s . 
Your way does not work when I open the classifier. There I unfortunately can not enter a GUID into the URL.
If I search a file via the Model Performance page, then the GUID is in the URL
I've tried it. If I copy the GUID to the URL then it works very well.
I would need for the test a way, as I can open a file directly, without any great circumstances, to test it or evaluate it.

**Comment by rassokhin-s** [comment]
hey @Starsonic007, now you can provide an audio guid using text input in the form. Does it good for you? I have not implemented "searching" for guid when user is typing it. If it's required, I can do that, just let me know. I just thought that it might be helpful when you have prepared guid and you just paste it in the field.
<img width="441" alt="screenshot_stanislav 2017-01-23 13 12 49" src="https://cloud.githubusercontent.com/assets/2122991/22199847/afc1e094-e16d-11e6-85da-cf1108580920.png">

**Comment by Starsonic007** [comment]
Thank you ... you have implemented very well. This helps me very much further if I search for special GUID's or something in this GUID want to change. I do only copy and past and thats fine for me. 
It works very well. thanks again
