### ISSUE TITLE
Remove old Detections page

### ISSUE THREAD

**Issue by rassokhin-s** [rfcx/rfcx-console#71]
... and clean up wavesurfer's directive.

**Comment by rassokhin-s** [comment]
@Starsonic007 please test Classifications page once again - I was refactoring a directive which is used on this page.

**Comment by Starsonic007** [comment]
I have checked the classification again completely. No error struck me. The calculation when 3 users have reviewed, is also correct. 
I have tested the calculation only with 1 file and 3 User . @rassokhin-s  , should I test more scenarios?
