### ISSUE TITLE
Classification: Decrease Confidence on Replay 

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#72]
_Note_: This will be an experimental feature. It would be great if we could turn it on and off easily. 

_Goal_: repeatedly listening to the same window may indicate that it is hard for the listener to figure out whether's it's a chainsaw or not. We'd like the vote of a person who listens to the sound 4 or 5 or more times to count less than the vote of someone who just heard it twice.  

_Currently_: we have only two settings for confidence: 0 and 1. 0 means that someone is sure it's ambient sound (not a chainsaw) and 1 means they are sure about it being a chainsaw. 

_Replay decays confidence_: We set a different confidence based on the number of times someone played the window; 

=if someone plays a window 1 or 2 times=
case chainsaw) they choose chainsaw => confidence=1 
case ambient) they choose ambient => confidence=0

=if someone plays a window 3 times=
case chainsaw) they choose chainsaw => confidence=0.9 
case ambient) they choose ambient => confidence=0.1

=if someone plays a window 4 times=
case chainsaw) they choose chainsaw => confidence=0.8 
case ambient) they choose ambient => confidence=0.2

=if someone plays a window 5 times=
case chainsaw) they choose chainsaw => confidence=0.7 
case ambient) they choose ambient => confidence=0.3

=if someone plays a window 6 times=
case chainsaw) they choose chainsaw => confidence=0.6 
case ambient) they choose ambient => confidence=0.4

=if someone plays a window 7 or more times=
case chainsaw) they choose chainsaw => confidence=0.5
case ambient) they choose ambient => confidence=0.5

_Adaptive Confidence Control_: The smaller the confidence, the less sure a person is about the label. For example 0.9 means that someone is pretty sure but has slight doubts. On the other hand 0.6 means they tend to believe it's a chainsaw but they have serious doubts. For 0.5, someone is completely unsure on whether it's a chainsaw. The same holds true for ambient sound. 0.1 means they are pretty certain about it being ambient sound and 0.4 means they tend to believe it's ambient but they not fully confident. 

<-ammbient-------total uncertainty-------chainsaw->
<-0--------------------0.5----------------------1-> 

By adapting the confidence on replay, we can represent a person's lack of confidence.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/167270113296771/168721306751466)

**Comment by rassokhin-s** [comment]
Hey @daebwae 
What about the following cases: 
1) When I heard a bird song in some window and want to replay it to enjoy it.
2) When I want to replay full audio file after I classified all windows - it might add one or more excess playbacks.

**Comment by rassokhin-s** [comment]
As a result of discussion in Slack we decided to do the following:
1) Add an additional column like `playback_count` for GuardianAudioTags
2) Count playbacks for each window and save this value into db
3) If user has played one window many times, show him popup like `whether they are just listening to the window for pleasure, or they are slightly unsure, have no clue or they wanted to make sure`. If user tells that he unsure, then we decrease confidence using the scheme above.
