### ISSUE TITLE
Sites -> Diagnostics Page: y-axis, repeated values

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#76]
![image](https://cloud.githubusercontent.com/assets/749854/17842046/1663f29c-681f-11e6-9ed6-5a6a1af11864.png)

On the y-axis in different graphs of the diagnostics page, there are repeated values. For example, here, we have -5 twice. We need to show different values for each label on the y-axis to understand what is going on. Maybe this is actually a float?

**Comment by Starsonic007** [comment]
Y-axis has been adjusted  --> TEST OK
![image](https://cloud.githubusercontent.com/assets/20114180/18230640/87bd6ab2-72a2-11e6-9a64-b866e53896d3.png)
