### ISSUE TITLE
Sites -> Diagnostics: Refresh Date-Time Slider

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#77]
If we go to the Diagnostics page and wait for 10 minutes, we cannot select the current time because it is outside of the right border of the slider. We need a way to refresh the slider so that we can select the current time.

Requirements: 
 - if the timespan includes the rightmost border and we press refresh, the slider extends to include the current time 
- additionally, we need to be able to refresh also when we have scrolled down the page and want to see the changes 

Optional, but it would be great: 
- We have a checkbox for "auto-updates". When we check it, the refresh is done every 30 seconds.

**Comment by rassokhin-s** [comment]
@daebwae actually, it was code for refreshing, but it was not working (though I was testing it some time ago...)
So I fixed it and set intervals for:
- timeline bounds refresh every 2 minutes
- timeline values along with charts data refresh every 10 minutes

**Comment by Starsonic007** [comment]
timeline bounds refresh every 2 minutes  --> TEST OK
timeline values along with charts data refresh every 10 minutes  --> TEST OK
