### ISSUE TITLE
All elements should be HTTPS

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx-console#8]
If anything on the page (scripts, images, CSS, fonts) aren't loaded over HTTPS, there will be errors. At the moment, the gravatar image, for example, is not secure:

![image](https://cloud.githubusercontent.com/assets/1895255/10268639/0946e99c-6abf-11e5-8e21-e7a5a6c73e8b.png)

**Comment by topherwhite** [comment]
I suspect this may be what's causing the map image loading error on the site picker as well. (it works for my locally, over http, but in production, over https, it does not load the images still)

**Comment by sweety-wo** [comment]
I have make sure to point every endpoint to https.. Thank you

**Comment by topherwhite** [comment]
I think this is working now. Thanks! I'll let you know if anything comes up in the future, but I can verify with you that the https had nothing to do with the map loading.
