### ISSUE TITLE
Download Page -> By Guids: Add the option to classify the files

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#80]
Currently: guids that don't have classifications will not be included in the download. 
Problem: I need to open up the classification window and copy and paste the guids into the address line to classify them. 
Goal: 
(1) If a guid is not found, they are listed as links that open up in a new tab in the classificator, so that I can quickly classify them. 
(2) We won't download them right away. 
(3) Instead, we give two options after the list: 
     (a) **retry** : this is for the use case when I classified all of them and then click this link to resubmit the same guids. 
     (b) **continue without these guids** : this is for the use case when I don't mind the missing guids and want to download them anyhow.

**Comment by Starsonic007** [comment]
About the GUID numbers, not yet rated Files can now be evaluated. -> TEST OK
For example, if 10 files are loaded and 3 of these are not rated, then these 3 files are displayed below .--> TEST OK
Each file can be evaluated via a button "Classify". Clicking on the button opens the Classificator. -> TEST OK
after reviewing a file, it will no longer appear in the list -> TEST OK
With the search individual files can be found from the list --> TEST OK
If you select another type Value, then also the viewfinder dentition changes --> TEST OK
