### ISSUE TITLE
N / A should not stand in the Precision column.

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-console#84]
Once a file has been evaluated by a model and a user, there can no stay  longer N / A  in the field Precision.

![image](https://cloud.githubusercontent.com/assets/20114180/18230809/04e5dfc0-72a7-11e6-8f91-38fc0cc8f746.png)

![image](https://cloud.githubusercontent.com/assets/20114180/18230819/32453f92-72a7-11e6-9125-1bcd98a0e97e.png)

**Comment by rassokhin-s** [comment]
@Starsonic007 Is it still an issue?

**Comment by Starsonic007** [comment]
N / A now no longer appears with a file, which has already been evaluated by a user and the model. 
-> TEST OK
