### ISSUE TITLE
Download Page, Classifier: Auto-Populate Dropdown

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#85]
Auto-populate Dropdown on Download page via the database -label values. 

`SELECT DISTINCT value FROM GuardianAudioTags where type='label'` 

We should use a new endpoint for this /tags/labels to retrieve an array of those labels. 

This endpoint should also be used in the window classification page to auto-populate the buttons.

**Comment by Starsonic007** [comment]
If you create in the Windows classifier a new custom tab, this also appears in the dropdown, under "Type Value" on the audio download page. 
TEST --> OK
