### ISSUE TITLE
Classificator: Remove Overlay

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#87]
When we classified a file, we get a green or red overlay. This overlay obscures the spetogram. The overlay should be replaced by a red/green border instead.

**Comment by rassokhin-s** [comment]
@daebwae I removed background, but added a small inner box-shadow, because if we use only border it's not so expressive. Please tell me if this shadow still obscures the view. Thanks.

**Comment by Starsonic007** [comment]
There are now only at the edge of a colored overlay

![image](https://cloud.githubusercontent.com/assets/20114180/18524371/6c918084-7ab8-11e6-9541-54c1bb5c6ecf.png)

**Comment by rassokhin-s** [comment]
@Starsonic007 should I change smth? Or can close the issue?

**Comment by Starsonic007** [comment]
For me it would be OK, but you had a question for Stefan asked and if he thinks that would be ok, the TASK can be closed.

**Comment by rassokhin-s** [comment]
@Starsonic007 ah yeah :)
actually, @daebwae said in Slack that he likes new design. Stefan, please confirm the UI design so we can close the issue :) Thanks!
