### ISSUE TITLE
Classificator: Add Window Numbers

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#88]
In the classificator add window numbers on top of each window starting with 1.

**Comment by rassokhin-s** [comment]
@daebwae just to make sure:
Let's imagine that I've opened 5 tabs with Classificators:
`1 Classificator`, `2 Classificator`, `3 Classificator`, `4 Classificator`, `5 Classificator`
Then I accidentally finished classifying `3 Classificator`, but others not.
Then opened a list of unclassified files and opened another new Classificator.
**Question**: what index should get this new tab? `6`?

**Comment by daebwae** [comment]
Sorry, there's a slight misunderstanding. I'll add more details.

Let's call each browser window a 'tab'. Within the classificator, we divide each Audio file into 'audio windows'. 

Sometimes, I want to tell someone "hey, I have seen a gunshot in window ... just a minute... let me count them". In this case, it would be great to see the audio window number on top. It's like the line numbers in editors.

**Comment by rassokhin-s** [comment]
@daebwae ah, sorry about that :) I thought this task is related to our recent multiple-tabs-classificator issue :)
now I understand that you want to count our 2sec windows of one audio file. Thanks.

**Comment by Starsonic007** [comment]
The individual sequence window now have a consecutive numbering --> TEST OK

![image](https://cloud.githubusercontent.com/assets/20114180/18524453/b8cd4c4e-7ab8-11e6-9a90-c2d3c88f3011.png)
