### ISSUE TITLE
Classificator: Go to next file

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#89]
We should have an option to listen to the next file in time from the same guardian. If we find an interesting phenomenon, we would like to continue listening to it.

**Comment by rassokhin-s** [comment]
@daebwae pushed to producton.
Now after saving all tags you'll see two new buttons: 
<img width="512" alt="screenshot_stanislav 2016-09-07 22 05 55" src="https://cloud.githubusercontent.com/assets/2122991/18324857/4c1a0d6a-7547-11e6-8f1d-23f5fec4e865.png">
`Load Another Random` acts like previous `Load` button - loads another random audio guid
`Load Next` loads next file after current audio based on `measured_at` attribute.

**Important note**: As long as we require to load next in time audio, we ignore all datafilters attributes which we apply while we load random audio when we press `Load Next` button - we just force loading next audio file. It can cause classifying one audio file by> 3 peoples.

**Comment by Starsonic007** [comment]
Works as expected  --> TEST OK
