### ISSUE TITLE
Guardian Selection (and further UI additions)

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx-console#9]
When a Guardian is "clicked/selected" from the list on the left, it should become highlighted, and the following should happen:

1. It should be highlighted on the map (this requires geo info to be updated for each guardian, so don't worry about this for now)
2. Below the map and list, a bunch of new information will become available. To begin, it there should be several tabs from left to right. For now, just create two tabs: Audio, Diagnostics
3. Diagnostics will be where we will put some of the graphs that you made before.
4. Audio is totally new, and this is what I'd like to ask you to work on first. This should be a WebAudio player and live Spectrogram of the audio that is available from `GET /v1/guardians/[:guardian_id]/audio`
5. Please take the initiative to start building this (functionality, not so much design) so that we can work out what's possible for the design together.

NOTE: That endpoint above has two behaviors, depending on what you put as the file extension of the URL. You should use both
`https://api.rfcx.org/v1/guardians/1feb704486c7/audio.json` returns JSON info on the latest audio to be sent from the guardian.
`https://api.rfcx.org/v1/guardians/1feb704486c7/audio.m4a` returns the audio file. The JSON file also includes a token-independent temporary URL for the audio file, in case you have difficulty encoding your own HTTP headers into the WebAudio player. 

Thanks!

**Comment by sweety-wo** [comment]
Done with required changes on this ticket.

**Comment by topherwhite** [comment]
Cool, thank you!
