### ISSUE TITLE
Multi-Download of files and fast connectivity

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-console#90]
When downloading a lot of audio files from the download tab on a high-speed internet connection, I get many download errors and end up with partial downloads. There might be a maximum of concurrent downloads in Chrome that we hit in these circumstances. Could you investigate this? Maybe we can add a delay between each download?

**Comment by rassokhin-s** [comment]
We haven't found this issue today - maybe it was related to API updates yesterday.
