### ISSUE TITLE
AudioDownload page: generate different types of csv

### ISSUE THREAD

**Issue by rassokhin-s** [rfcx/rfcx-console#91]
**Types**:
(1) d633c8bf-ec12-4d18-b74e-0dcc05fdbd4b,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
(2) d633c8bf-ec12-4d18-b74e-0dcc05fdbd4b.wav    0    24000    ambient
(3) d633c8bf-ec12-4d18-b74e-0dcc05fdbd4b,0,24000,ambient

Names of buttons:
(1) original , (2) tsv, (3) csv

**Comment by Starsonic007** [comment]
Works as expected  --> TEST OK 
All formats can be downloaded --> TEST OK
